version: '2'
services:
  zookeeper:
    image: zll5267/zookeeper
    ports:
      - "2181:2181"
  zkwebui:
    image: zll5267/zookeeper-webui
    environment:
      ZK_DEFAULT_NODE: zookeeper:2181
      HTTP_PORT: 8080
      USER: zll
      PASSWORD: zll
    ports:
      - "8080:8080"
  kafka:
    image: zll5267/kafka:2.13-2.7.0
    depends_on:
      - zookeeper
    ports:
      - "9092"
    environment:
      DOCKER_API_VERSION: 1.22
      KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafkamanager:
    depends_on:
      - zookeeper
      - kafka
    image: zll5267/kafka-manager:3.0.0.4
    environment:
      ZK_HOSTS: zookeeper:2181
    ports:
      - "9000:9000"
